# Generated by Django 6.0.5 on 2026-05-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(default='Material', max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
