# Generated by Django 6.0.5 on 2026-05-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_course_options_alter_program_options_and_more'),
        ('users', '0002_institute_remove_user_institution_id_user_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='institution_id',
        ),
        migrations.AddField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.institute'),
        ),
        migrations.AddField(
            model_name='module',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='users.institute'),
        ),
        migrations.AddField(
            model_name='program',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='users.institute'),
        ),
        migrations.AddField(
            model_name='topic',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='users.institute'),
        ),
    ]
