# Generated by Django 6.0.5 on 2026-05-15 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_initial'),
        ('curriculum', '0003_alter_course_options_alter_program_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='curriculum.topic'),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
