# Generated by Django 6.0.5 on 2026-05-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
        ('users', '0002_institute_remove_user_institution_id_user_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.institute'),
        ),
    ]
